### ISSUE TITLE
ncm-ceph - removed osd prevents deploy of new nodes.

### ISSUE THREAD

**Issue by apdibbo** [quattor/configuration-modules-core#419]
We currently have a faulty disk in one of our nodes and a number of new nodes ready to be deployed.

The faulty disk has been downed, removed from the crush map and unmounted from the storage node. The cluster is HEALTH_OK however when we run "quattor-configure ceph" on our deploy node to deploy the new nodes it seems to attempt to re add the old faulted disk and errors.

The errors in the configure output are below
```
[sn5.nubes.rl.ac.uk][INFO  ] checking OSD status...
[sn5.nubes.rl.ac.uk][INFO  ] Running command: sudo ceph --cluster=ceph osd stat --format=json
[ceph_deploy.osd][DEBUG ] Host sn5.nubes.rl.ac.uk is now ready for osd use.

[VERB] Executing command: su - ceph -c /usr/bin/ceph-deploy --cluster ceph osd activate sn5.nubes.rl.ac.uk:/var/lib/ceph/osd/sdb
[VERB] Command options: stderr=SCALAR(0x337f8e0) stdout=SCALAR(0x361b2f0)
[ERROR] Command failed. Error Message: [ceph_deploy.conf][DEBUG ] found configuration file at: /home/ceph/.cephdeploy.conf
[ceph_deploy.cli][INFO  ] Invoked (1.5.11): /usr/bin/ceph-deploy --cluster ceph osd activate sn5.nubes.rl.ac.uk:/var/lib/ceph/osd/sdb
[ceph_deploy.osd][DEBUG ] Activating cluster ceph disks sn5.nubes.rl.ac.uk:/var/lib/ceph/osd/sdb:
[sn5.nubes.rl.ac.uk][DEBUG ] connected to host: sn5.nubes.rl.ac.uk
[sn5.nubes.rl.ac.uk][DEBUG ] detect platform information from remote host
[sn5.nubes.rl.ac.uk][DEBUG ] detect machine type
[ceph_deploy.osd][INFO  ] Distro info: Scientific Linux 6.4 Carbon
[ceph_deploy.osd][DEBUG ] activating host sn5.nubes.rl.ac.uk disk /var/lib/ceph/osd/sdb
[ceph_deploy.osd][DEBUG ] will use init type: sysvinit
[sn5.nubes.rl.ac.uk][INFO  ] Running command: sudo ceph-disk -v activate --mark-init sysvinit --mount /var/lib/ceph/osd/sdb
[sn5.nubes.rl.ac.uk][WARNING] DEBUG:ceph-disk:Cluster uuid is 38f90dd9-f7a8-40fd-b8b8-2b207b6bfc85
[sn5.nubes.rl.ac.uk][WARNING] INFO:ceph-disk:Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
[sn5.nubes.rl.ac.uk][WARNING] libust[1504361/1504361]: Warning: HOME environment variable not set. Disabling LTTng-UST per-user tracing. (in setup_local_apps() at lttng-ust-comm.c:305)
[sn5.nubes.rl.ac.uk][WARNING] DEBUG:ceph-disk:Cluster name is ceph
[sn5.nubes.rl.ac.uk][WARNING] DEBUG:ceph-disk:OSD uuid is 4f83c81d-53df-43fd-9925-3d01df98f2f4
[sn5.nubes.rl.ac.uk][WARNING] DEBUG:ceph-disk:Allocating OSD id...
[sn5.nubes.rl.ac.uk][WARNING] INFO:ceph-disk:Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd create --concise 4f83c81d-53df-43fd-9925-3d01df98f2f4
[sn5.nubes.rl.ac.uk][WARNING] libust[1504364/1504364]: Warning: HOME environment variable not set. Disabling LTTng-UST per-user tracing. (in setup_local_apps() at lttng-ust-comm.c:305)
[sn5.nubes.rl.ac.uk][WARNING] DEBUG:ceph-disk:OSD id is 202
[sn5.nubes.rl.ac.uk][WARNING] DEBUG:ceph-disk:Initializing OSD...
[sn5.nubes.rl.ac.uk][WARNING] INFO:ceph-disk:Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/osd/sdb/activate.monmap
[sn5.nubes.rl.ac.uk][WARNING] libust[1504396/1504396]: Warning: HOME environment variable not set. Disabling LTTng-UST per-user tracing. (in setup_local_apps() at lttng-ust-comm.c:305)
[sn5.nubes.rl.ac.uk][WARNING] got monmap epoch 3
[sn5.nubes.rl.ac.uk][WARNING] INFO:ceph-disk:Running command: /usr/bin/ceph-osd --cluster ceph --mkfs --mkkey -i 202 --monmap /var/lib/ceph/osd/sdb/activate.monmap --osd-data /var/lib/ceph/osd/sdb --osd-journal /var/lib/ceph/osd/sdb/journal --osd-uuid 4f83c81d-53df-43fd-9925-3d01df98f2f4 --keyring /var/lib/ceph/osd/sdb/keyring
[sn5.nubes.rl.ac.uk][WARNING] libust[[sn5.nubes.rl.ac.uk][WARNING] got monmap epoch 3
[sn5.nubes.rl.ac.uk][WARNING] INFO:ceph-disk:Running command: /usr/bin/ceph-osd --cluster ceph --mkfs --mkkey -i 202 --monmap /var/lib/ceph/osd/sdb/activate.monmap --osd-data /var/lib/ceph/osd/sdb --osd-journal /var/lib/ceph/osd/sdb/journal --osd-uuid 4f83c81d-53df-43fd-9925-3d01df98f2f4 --keyring /var/lib/ceph/osd/sdb/keyring
[sn5.nubes.rl.ac.uk][WARNING] libust[1504501/1504501]: Warning: HOME environment variable not set. Disabling LTTng-UST per-user tracing. (in setup_local_apps() at lttng-ust-comm.c:305)
[sn5.nubes.rl.ac.uk][WARNING] 2015-02-12 15:24:29.470992 7f07d1b33800 -1 journal FileJournal::_open: disabling aio for non-block journal.  Use journal_force_aio to force use of aio anyway
[sn5.nubes.rl.ac.uk][WARNING] 2015-02-12 15:24:29.486009 7f07d1b33800 -1 journal FileJournal::_open_file : unable to preallocation journal to 10737418240 bytes: (22) Invalid argument
[sn5.nubes.rl.ac.uk][WARNING] 2015-02-12 15:24:29.486031 7f07d1b33800 -1 filestore(/var/lib/ceph/osd/sdb) mkjournal error creating journal on /var/lib/ceph/osd/sdb/journal: (22) Invalid argument
[sn5.nubes.rl.ac.uk][WARNING] 2015-02-12 15:24:29.486051 7f07d1b33800 -1 OSD::mkfs: ObjectStore::mkfs failed with error -22
[sn5.nubes.rl.ac.uk][WARNING] 2015-02-12 15:24:29.486115 7f07d1b33800 -1  ** ERROR: error creating empty object store in /var/lib/ceph/osd/sdb: (22) Invalid argument
[sn5.nubes.rl.ac.uk][WARNING] Traceback (most recent call last):
[sn5.nubes.rl.ac.uk][WARNING]   File "/usr/sbin/ceph-disk", line 2792, in <module>
[sn5.nubes.rl.ac.uk][WARNING]     main()
[sn5.nubes.rl.ac.uk][WARNING]   File "/usr/sbin/ceph-disk", line 2770, in main
[sn5.nubes.rl.ac.uk][WARNING]     args.func(args)
[sn5.nubes.rl.ac.uk][WARNING]   File "/usr/sbin/ceph-disk", line 2011, in main_activate
[sn5.nubes.rl.ac.uk][WARNING]     init=args.mark_init,
[sn5.nubes.rl.ac.uk][WARNING]   File "/usr/sbin/ceph-disk", line 1841, in activate_dir
[sn5.nubes.rl.ac.uk][WARNING]     (osd_id, cluster) = activate(path, activate_key_template, init)
[sn5.nubes.rl.ac.uk][WARNING]   File "/usr/sbin/ceph-disk", line 1943, in activate
[sn5.nubes.rl.ac.uk][WARNING]     keyring=keyring,
[sn5.nubes.rl.ac.uk][WARNING]   File "/usr/sbin/ceph-disk", line 1573, in mkfs
[sn5.nubes.rl.ac.uk][WARNING]     '--keyring', os.path.join(path, 'keyring'),
[sn5.nubes.rl.ac.uk][WARNING]   File "/usr/sbin/ceph-disk", line 316, in command_check_call
[sn5.nubes.rl.ac.uk][WARNING]     return subprocess.check_call(arguments)
[sn5.nubes.rl.ac.uk][WARNING]   File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
[sn5.nubes.rl.ac.uk][WARNING]     raise CalledProcessError(retcode, cmd)
[sn5.nubes.rl.ac.uk][WARNING] subprocess.CalledProcessError: Command '['/usr/bin/ceph-osd', '--cluster', 'ceph', '--mkfs', '--mkkey', '-i', '202', '--monmap', '/var/lib/ceph/osd/sdb/activate.monmap', '--osd-data', '/var/lib/ceph/osd/sdb', '--osd-journal', '/var/lib/ceph/osd/sdb/journal', '--osd-uuid', '4f83c81d-53df-43fd-9925-3d01df98f2f4', '--keyring', '/var/lib/ceph/osd/sdb/keyring']' returned non-zero exit status 1
[sn5.nubes.rl.ac.uk][ERROR ] RuntimeError: command returned non-zero exit status: 1
[ceph_deploy][ERROR ] RuntimeError: Failed to execute command: ceph-disk -v activate --mark-init sysvinit --mount /var/lib/ceph/osd/sdb

1504501/1504501]: Warning: HOME environment variable not set. Disabling LTTng-UST per-user tracing. (in setup_local_apps() at lttng-ust-comm.c:305)
```

Would it be possible to get a way to either automatically test OSDs and then skip faulted OSDs or to opt to skip particular OSDs?

At the moment we will need to take the whole node out in order to put our new nodes in which will not really be workable when we are operating at scale.

**Comment by kwaegema** [comment]
You can skip this particular OSD by removing it from the template. (Right now it sees in the template you want an OSD there, so by design tries to reinstall it :smile: )
When you replaced the disk then , you should re-add it in the profile.
This was also discussed in #317 with @jrha , and we don't have a clean solution yet.
I could add an option to ignore OSD errors, but that will of course also mask unintentional errors..

**Comment by apdibbo** [comment]
Hi Kenneth, that sounds like it would be great however we have all of the disks for our storage nodes defined as part of the model so my understanding is that we can't do this. 
Thanks
Alex

**Comment by kwaegema** [comment]
I can't completely understand, but you probably should set that one disk of that one host to undef after the whole `osdhost` tree has been generated.

**Comment by apdibbo** [comment]
Unfortunately there is no support for host specific overrides in Aquilon so I do not believe this is possible.
Thanks
Alex

**Comment by kwaegema** [comment]
support for this was added in #520
